[mypy]
python_version = 3.11

[mypy-gradio_client.*]
ignore_missing_imports = True

[mypy-insightface.*]
ignore_missing_imports = True

[mypy-psutil.*]
ignore_missing_imports = True

[mypy-replicate.*]
ignore_missing_imports = True

[mypy-src.api.routes.generation]
disable_error_code = arg-type, assignment, call-overload, return-value

[mypy-src.api.routes.privacy]
disable_error_code = arg-type

[mypy-src.api.routes.products]
disable_error_code = arg-type

[mypy-src.config.settings]
disable_error_code = call-arg, call-overload

[mypy-src.modules.image_generator.catvton_generator]
disable_error_code = assignment, misc

[mypy-src.modules.privacy_guard.face_anonymizer]
disable_error_code = assignment, call-overload

[mypy-src.utils.error_handlers]
disable_error_code = misc, return-value, union-attr
